version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
    - "27017:27017"
  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
    - "5672:5672"
    - "15672:15672"
    environment:
    - RABBITMQ_PASSWORD=password
  rating-api:
    image: 'canyan/rating-api:master'
    command: rating-api --host 0.0.0.0 --port 8000
    ports:
    - "8000:8000"
    environment:
    - RATING_API_MONGODB_URI=mongodb://mongodb:27017
